name: Gov Cloud Market

author:
  name: 18F
  url: https://18f.gsa.gov

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

styles:
  - assets/css/styles.css

repos:
- name: Cloud marketplaceholder
  description: Main repository
  url: https://github.com/18F/cloud-marketplaceholder
